src/AbsenceBundle/Entity/absence.php
<?php

namespace AbsenceBundle\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use AppBundle\Entity\User;
use Doctrine\ORM\Mapping as ORM;

/**
 * absence
 *
 * @ORM\Table(name="absence")
 * @ORM\Entity(repositoryClass="AbsenceBundle\Repository\absenceRepository")
 */
class absence implements \JsonSerializable
{
    /**
     * @var int
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $idabsence;
    /**
     * @ORM\Column(type="integer")
     */
    private $id_user;

    /**
     * @return int
     */
    public function getIdUser()
    {
        return $this->id_user;
    }

    /**
     * @param int $id_user
     */
    public function setIdUser($id_user)
    {
        $this->id_user = $id_user;
    }

    /**
     *
     * @ORM\Column(type="integer")
     */
    private $absence;

    /**
     * @var string
     *
     * @ORM\Column(name="Image_Event", type="string", length=255, nullable=true)
     */
    private $imageEvent;
    /**
     * @ORM\Column(type="integer")
     */
    private $id_classe;
    /**
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User")
     * @ORM\JoinColumn(name="id_user",referencedColumnName="id")
     */
    private $user;
    /**
     *
     * @ORM\ManyToOne(targetEntity="sceance")
     * @ORM\JoinColumn(name="id_seance",referencedColumnName="id_seance")
     */
    private $sceance;
    /**
     * @ORM\ManyToOne(targetEntity="ClasseBundle\Entity\Classe")
     * @ORM\JoinColumn(name="id_classe",referencedColumnName="id_classe")
     */
    private $classe;
    /**
     * @ORM\ManyToOne(targetEntity="NoteBundle\Entity\Matiere")
     * @ORM\JoinColumn(name="id_matiere",referencedColumnName="id_matiere")
     */
    private $matiere;

    /**
     * @return mixed
     */
    public function getClasse()
    {
        return $this->classe;
    }

    /**
     * @param mixed $classe
     */
    public function setClasse($classe)
    {
        $this->classe = $classe;
    }

    /**
     * @return mixed
     */
    public function getMatiere()
    {
        return $this->matiere;
    }

    /**
     * @param mixed $matiere
     */
    public function setMatiere($matiere)
    {
        $this->matiere = $matiere;
    }


    /**
     * @return mixed
     */
    public function getSceance()
    {
        return $this->sceance;
    }

    /**
     * @param mixed $sceance
     */
    public function setSceance($sceance)
    {
        $this->sceance = $sceance;
    }


    /**
     * @return int
     */
    public function getIdabsence()
    {
        return $this->idabsence;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

    /**
     * @param int $idabsence
     */
    public function setIdabsence($idabsence)
    {
        $this->idabsence = $idabsence;
    }


    /**
     * @return int
     */
    public function getIdSeance()
    {
        return $this->id_seance;
    }

    /**
     * @param int $id_seance
     */
    public function setIdSeance($id_seance)
    {
        $this->id_seance = $id_seance;
    }

    /**
     * @return int
     */
    public function getAbsence()
    {
        return $this->absence;
    }

    /**
     * @param int $absence
     */
    public function setAbsence($absence)
    {
        $this->absence = $absence;
    }


    /**
     * @return int
     */
    public function getIdClasse()
    {
        return $this->id_classe;
    }

    /**
     * @param int $id_classe
     */
    public function setIdClasse($id_classe)
    {
        $this->id_classe = $id_classe;
    }

    /**
     * @return string
     */
    public function getImageEvent()
    {
        return $this->imageEvent;
    }

    /**
     * @param string $imageEvent
     */
    public function setImageEvent($imageEvent)
    {
        $this->imageEvent = $imageEvent;
    }

    /**
     * @inheritDoc
     */
    public function jsonSerialize()
    {
        return [
            "id" => $this->idabsence,
            "abs" => $this->absence,
            "user" => $this->getUser(),
            "classe" => $this->getClasse(),
            "sceance" => $this->getSceance(),
            "matiere" => $this->getMatiere()
        ];
    }

}

src/AbsenceBundle/Controller/DefaultController.php
<?php

namespace AbsenceBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function indexAction()
    {
        return $this->render('AbsenceBundle:Default:index1.html.twig');
    }





}

src/AbsenceBundle/Resources/views/Default/Rechercheclasse.html.twig
{% extends "::front/common/layout.html.twig" %}
{% block body %}
<div class="postbar postbarNone post-5426 page type-page status-publish hentry">
    {% block header %}
        <div class="page-header">
            <noscript>
                <img alt="Events"
                     class="page-header-img"/>
            </noscript>
            <img alt="Events" class="page-header-img lazyloaded"
                 data-src="{{ asset('wp-content/uploads/2018/05/milan-2698731_1920-1500x750.jpg') }}"
                 src="{{ asset('wp-content/uploads/2018/05/milan-2698731_1920-1500x750.jpg') }}">
            <div class="container"><h1 class="give-form-title entry-title" itemprop="headline">Gestion Absence</h1>
            </div>
        </div>
    {% endblock %}

    {% block content %}
{{ form(f) }}

<table border="1">
    <tr>
        <th>Cin étudiant</th>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Numéro de séance</th>
        <th>Nombre absence</th>

    </tr>
    {% for elt in absence     %}
    <tr>

        <td>{{ elt.user.CIN }}</td>
        <td>{{ elt.user.FirstName}}</td>
        <td>{{ elt.user.LastName}}</td>
        <td>{{ elt.sceance.IdSeance}}</td>
        <td>{{ elt.Absence}}</td>
        <td style="background: none;border-right: none   " >
        <span style="width: 113px;">
        <a type="button" class="btn btn-success btn-icon-sm" href="{{ path('absence_deleteabs',{'id':elt.Idabsence})}}"style="margin-left: 20%">
                <i class="flaticon2-plus"></i>Supprimer</a>
            </span>
        </td>
    </tr>
    {% endfor %}


</table>
 {% endblock %}
{% endblock %}

src/AbsenceBundle/Resources/views/Default/Rechercheclasseadmin.html.twig
{% extends "::back/common/layout.html.twig" %}


    {% block body %}
        {% if app.user.hasRole('ROLE_SUPER_ADMIN') %}
        <div class="form-style-5" style="margin-top: 100px">
{{ form(f) }}
        </div>

<table border="1">
    <tr>
        <th>Cin étudiant</th>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Numéro de séance</th>
        <th>Nombre absence</th>

    </tr>
    {% for elt in absence     %}
    <tr>

        <td>{{ elt.user.CIN }}</td>
        <td>{{ elt.user.FirstName}}</td>
        <td>{{ elt.user.LastName}}</td>
        <td>{{ elt.sceance.IdSeance}}</td>
        <td>{{ elt.Absence}}</td>
        <td>
            <a onclick="confirm('Voulez-vous vraiment supprimer le matiére ')" href="{{ path('absence_delete',{'id':elt.Idabsence})}}">
                <button type="button" class="btn btn-outline-danger waves-effect waves-light m-1">
                    Supprimer</button></a>

        </td>

    </tr>
    {% endfor %}


</table>
{% endif %}
{% endblock %}

src/AbsenceBundle/Resources/views/Default/addabsence.html.twig
{% extends "::front/common/layout.html.twig" %}

{% block title %}Absence{% endblock %}


{% block body %}
    <div class="postbar postbarNone post-5426 page type-page status-publish hentry">
        {% block header %}
            <div class="page-header">
                <noscript>
                    <img alt="Events"
                         class="page-header-img"
                         src="{{ asset('wp-content/uploads/2019/09/teacher-1280966_1920-1500x750.jpg') }}"/>
                </noscript>
                <img alt="Events" class="page-header-img lazyloaded"
                     data-src="{{ asset('wp-content/uploads/2019/09/teacher-1280966_1920-1500x750.jpg') }}"
                     src="{{ asset('wp-content/uploads/2019/09/teacher-1280966_1920-1500x750.jpg') }}">
                <div class="container"><h1 class="give-form-title entry-title" itemprop="headline">Absence</h1>
                </div>
            </div>
        {% endblock %}
        {% block content %}
            <div class="container page tmnf_page">
                <div id="core">
                    <div class="entry">
                        <div id="em-wrapper">

                            <div class="text-center" style="text-align: center">
                                <div class="elementor-element elementor-element-2e1ccd32 elementor-widget elementor-widget-heading">
                                    <div class="elementor-widget-container">
                                        <h5 class="elementor-heading-title elementor-size-default">
                                            Feel
                                            free
                                            to fill your <br>absence</h5>
                                    </div>
                                </div>
                                <div class="elementor-element elementor-widget elementor-widget-divider">
                                    <div class="elementor-widget-container">
                                        <div class="elementor-divider">
                                            <span class="elementor-divider-separator"> </span></div>
                                    </div>
                                </div>
                            </div>

                            <div aria-hidden="true" class="wp-block-spacer" style="height:73px"></div>

                            <div class="css-events-list">
                                <table class="events-table">
                                    <div class="container col-md-4">
                                        <div class="card-body">
                                            {{ form_start(f) }}
                                            {{ form_widget(f) }}
                                            {{ form_end(f) }}
                                        </div>
                                    </div>

                                    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css"
                                          rel="stylesheet"/>

                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        {% endblock %}
    </div>
{% endblock %}
{% block js %}
    <script src="{{ asset('assets/js/components/vendor/select2.js') }}"></script>
    <script type="text/javascript">
        (function ($) {
            $('.select2').select2();
        })(jQuery);
    </script>
{% endblock %}

src/AbsenceBundle/Resources/views/Default/ajout.html.twig
{% extends "::back/common/layout.html.twig" %}

{% block body %}
    {% if app.user.hasRole('ROLE_SUPER_ADMIN') %}
    <div class="form-style-5" style="margin-top: 100px">
{{ form(f) }}
    </div>
    {% endif %}
{% endblock %}

src/AbsenceBundle/Resources/views/Default/etudiant.html.twig
{% extends "::front/common/layout.html.twig" %}

{% block body %}
<div class="postbar postbarNone post-5426 page type-page status-publish hentry">
    {% block header %}
        <div class="page-header">
            <noscript>
                <img alt="Events"
                     class="page-header-img"/>
            </noscript>
            <img alt="Events" class="page-header-img lazyloaded"
                 data-src="{{ asset('wp-content/uploads/2018/05/milan-2698731_1920-1500x750.jpg') }}"
                 src="{{ asset('wp-content/uploads/2018/05/milan-2698731_1920-1500x750.jpg') }}">
            <div class="container"><h1 class="give-form-title entry-title" itemprop="headline">Absence</h1>
            </div>
        </div>
    {% endblock %}
    {% block content %}
        <div class="container page tmnf_page">
            <div id="core">
                <div class="entry">
                    <div id="em-wrapper">
                        {% if app.user.hasRole('ROLE_STUDENT') %}
                            <h2> votre absence : </h2>
                            <style>
                                #table {
                                    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
                                    border-collapse: collapse;
                                    width: 100%;
                                }

                                #table td, #table th {
                                    border: 1px solid #ddd;
                                    padding: 8px;
                                }

                                #table tr:nth-child(even) {
                                    background-color: #f2f2f2;
                                }

                                #table tr:hover {
                                    background-color: #ddd;
                                }

                                #table th {
                                    padding-top: 12px;
                                    padding-bottom: 12px;
                                    text-align: left;
                                    background-color: #640bc3;
                                    color: white;
                                }

                                #TitreBO {
                                    font-size: 48px;
                                    text-shadow: -1px -1px black, 1px 1px #a00, -3px 0 4px #000;
                                    font-family: "Segoe print", Arial, Helvetica, sans-serif;
                                    color: #8bc34a;
                                    padding: 64px 0 0 0;
                                    margin: 16px auto;
                                    font-weight: lighter;
                                    -moz-box-shadow: none;
                                    -webkit-box-shadow: none;
                                    box-shadow: black;
                                    text-align: center;
                                    display: block;
                                }
                            </style>
                            <table id="table" class="table-responsive">
                                <thead>
                                <tr>
                                    <th>
                                        <span>Cin étudiant</span>
                                    </th>
                                    <th>
                                        <span>Nom</span>
                                    </th>
                                    <th>
                                        <span>Prénom</span>
                                    </th>
                                    <th>
                                        <span>Numéro de séance</span>
                                    </th>
                                    <th>
                                        <span>Classe</span>
                                    </th>
                                    <th>
                                        <span>Matiére</span>
                                    </th>
                                    <th>
                                        <span>Nombre absence</span>
                                    </th>
                                    <th>
                                        <span>Remarque</span>
                                    </th>

                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    {% for elt in absences %}
                                        <td>
                                            <span>{{ elt.user.CIN }}</span>
                                        </td>
                                        <td>
                                            <span>{{ elt.user.FirstName }}</span>
                                        </td>
                                        <td>
                                            <span>{{ elt.user.LastName }}</span>
                                        </td>
                                        <td>
                                            <span>{{ elt.sceance.IdSeance }}</span>
                                        </td>
                                        <td>
                                            <span>{{ elt.Classe.NumClasse }}</span>
                                        </td>
                                        <td>
                                            <span>{{ elt.Matiere.NomMat }}</span>
                                        </td>
                                        <td>
                                            <span>{{ elt.Absence }}</span>
                                        </td>
                                        {#<td align="center"><a href="file://C:\wamp64\www\unitech\public1\uploads\{{ elt.getImageEvent() }}   " target="_blank">link text</a>  </td>#}
                                        <td align="center" style="max-width: 30px">
                                            <a href="{{ asset('public1/uploads/' ~ elt.getImageEvent()) }}">
                                                <img src="{{ asset('public1/uploads/' ~ elt.getImageEvent()) }}">
                                            </a>
                                        </td>

                                    {% endfor %}
                                </tr>
                                </tbody>
                            </table>
                        {% endif %}
                        <div class="container text-center">
                            {% for x in test %}
                                {{ barcode({code: 'In total you have '~ x.Absence |trans ~ ' Absence!', type: 'qrcode', format: 'svg', width: 10, height: 10, color: 'black'}) }}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>


    {% endblock %}

    {% endblock %}

src/AbsenceBundle/Resources/views/Default/index.html.twig
Hello World!

src/AbsenceBundle/Resources/views/Default/read.html.twig
{% extends "::back/common/layout.html.twig" %}
{% block body %}
    {% if app.user.hasRole('ROLE_SUPER_ADMIN') %}
<div class="col-lg-12">
    <div class="card">
        <div class="card-header"><i class="fa fa-table"></i> Liste de séance</div>
        <div class="card-body">
            <style>
                .alert-success {
                    color: #fff;
                    border-color: #87908c;
                    background-color: #afb3b1;
                    width: 50%;
                }
            </style>
            <center>
                {% for message in app.flashes('successmodif') %}
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                {% endfor %}
            </center>

            <div class="table-responsive">
                <table id="default-datatable" class="table table-bordered">
                    <thead>


    <tr>
        <th>Numéro de seance</th>
        <th>heure</th>
        <th>jour</th>
    </tr>
    </thead>
    <tbody >
    <tr>
    {% for elt in sceances     %}

        <td>
           {{ elt.idSeance }}
        </td>
        <td>
           {{ elt.heure|date}}
        </td>
        <td>
            {{ elt.jour }}
        </td>
        <td>
        <a  href="{{ path('absence_delete',{'id':elt.idSeance})}}">
            <button type="button" class="btn btn-outline-danger waves-effect waves-light m-1">
        Supprimer</button></a>

        </td>
       <td>
        <a  href="{{ path('absence_update',{'id':elt.idSeance})}}">
            <button type="button" class="btn btn-outline-danger waves-effect waves-light m-1">
                Modifier</button></a>
                        </td>

    </tr>
    {% endfor %}

    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>
{% endif %}


{% endblock %}

src/AbsenceBundle/Resources/views/Default/read1.html.twig
{% extends "::front/common/layout.html.twig" %}
{% block body %}
    <div class="postbar postbarNone post-5426 page type-page status-publish hentry">
        {% block header %}
            <div class="page-header">
                <noscript>
                    <img alt="Events"
                         class="page-header-img"/>
                </noscript>
                <img alt="Events" class="page-header-img lazyloaded"
                     data-src="{{ asset('wp-content/uploads/2018/05/milan-2698731_1920-1500x750.jpg') }}"
                     src="{{ asset('wp-content/uploads/2018/05/milan-2698731_1920-1500x750.jpg') }}">
                <div class="container"><h1 class="give-form-title entry-title" itemprop="headline">Gestion Absence</h1>
                </div>
            </div>
        {% endblock %}
{% block content %}



<h2> les absences des étudiants </h2>

    <style>
        .alert-success {
            color: #fff;
            border-color: #87908c;
            background-color: #afb3b1;
            width: 50%;
        }
    </style>
    <center>
        {% for message in app.flashes('successmodif') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
    </center>

    <style>
    #table {
        font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    #table td, #table th {
        border: 1px solid #ddd;
        padding: 8px;
    }

    #table tr:nth-child(even){background-color: #f2f2f2;}

    #table tr:hover {background-color: #ddd;}

    #table th {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #640bc3;
        color: white;
    }
    #TitreBO
    {
        font-size: 48px;
        text-shadow: -1px -1px black, 1px 1px #a00, -3px 0 4px #000;
        font-family:"Segoe print", Arial, Helvetica, sans-serif;
        color: #8bc34a;
        padding:64px 0 0 0;
        margin:16px auto;
        font-weight:lighter;
        -moz-box-shadow:none;
        -webkit-box-shadow: none;
        box-shadow:black;
        text-align:center;
        display:block;
    }
</style>

<table id="table" style="margin-left: 51px;margin-top: 5%">
    <thead >
    <tr>
        <th>
            <span style="width: 90px;">Cin</span>
        </th>
        <th>
            <span style="width: 90px;">Nom</span>
        </th>
        <th>
            <span style="width: 90px;">Prénom</span>
        </th>
        <th>
            <span style="width: 90px;">Numéro de séance</span>
        </th>
        <th>
            <span style="width: 90px;">Classe</span>
        </th>
        <th>
            <span style="width: 90px;">Matiére</span>
        </th>
        <th>
            <span style="width: 90px;">Nombre absence</span>
        </th>

        <th>
            <span style="width: 90px;">Remarque</span>
        </th>

      </tr>
    </thead>
    <tbody >
    <tr>
      {% for elt in absences     %}


     <td>
         <span style="width: 90px;">{{ elt.user.CIN }}</span>
     </td>
      <td>
          <span style="width: 90px;">{{ elt.user.FirstName}}</span>
      </td>
      <td>
          <span style="width: 90px;">{{ elt.user.LastName}}</span>
      </td>
    <td>
        <span style="width: 90px;">{{ elt.sceance.IdSeance}}</span>
    </td>
    <td>
        <span style="width: 90px;">{{ elt.Classe.NumClasse}}</span>
   </td>
   <td>
       <span style="width: 90px;">{{ elt.Matiere.NomMat}}</span>
   </td>
    <td>
        <span style="width: 90px;">{{ elt.Absence}}</span>
       {# {{ barcode({code: 'In total you have '~ elt.Absence |trans ~ ' Absence!', type: 'qrcode', format: 'svg', width: 10, height: 10, color: 'black'}) }}#}

    </td>
        <td align="center"><a href="/unitech/public1/uploads\{{ elt.getImageEvent() }} "><img src="/unitech\public1\uploads\{{ elt.getImageEvent() }}   "></a>  </td>




        <td style="background: none;border-right: none   " >
        <span style="width: 113px;">
        <a type="button" class="btn btn-success btn-icon-sm" href="{{ path('absence_deleteabs',{'id':elt.Idabsence})}}"style="margin-left: 20%">
                <i class="flaticon2-plus"></i>Supprimer</a>
            </span>
        </td>
        <td style="background: none;border-right: none   " >
        <span style="width: 113px;">
        <a type="button" class="btn btn-success btn-icon-sm" href="{{ path('absence_updateabs',{'id':elt.Idabsence})}}"style="margin-left: 20%">
                 <i class="flaticon2-plus"></i>modifier</a>
            </span>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>


{% endblock %}
{% endblock %}

src/AbsenceBundle/Resources/views/Default/recherche.html.twig
{% extends "::back/common/layout.html.twig" %}
{% block body %}
    {% if app.user.hasRole('ROLE_SUPER_ADMIN') %}
<h2> Recherche sceance par jour</h2>


    <div class="col-lg-12">
        <div class="card">
            <div class="card-header"><i class="fa fa-table"></i> Liste de séance</div>
            <div class="card-body">
                <div class="table-responsive">
                   <form method="post">
                        <input type="text" name="jour">
                        <input type="submit" value="recherche">
                    </form>
                    <a style="margin-left: 900px" href="{{ path('absence_ajoutsceance') }}" class="btn btn-sm btn-primary btn-create"> <b>+</b> ajouter scéance</a>

                    <table class="table" id="myTable">

                        <thead>


                        <tr>
                            <th>Numéro de seance</th>
                            <th>heure</th>
                            <th>jour</th>
                            <th>supprimer</th>
                            <th>modifier</th>
                        </tr>
                        </thead>
                        <tbody >
                        <tr>
                            {% for elt in sceance     %}

                            <td>
                                {{ elt.idSeance }}
                          </td>
                            <td>
                                {{ elt.heure|date}}
                            </td>
                            <td>
                                {{ elt.jour }}
                            </td>
                        <td>
                                <a onclick="confirm('Voulez-vous vraiment supprimer le matiére ')" href="{{ path('absence_delete',{'id':elt.idSeance})}}">
                                    <button type="button" class="btn btn-outline-danger waves-effect waves-light m-1">
                                        Supprimer</button></a>

                            </td>
                            <td>
                                <a  href="{{ path('absence_update',{'id':elt.idSeance})}}">
                                    <button type="button" class="btn btn-outline-danger waves-effect waves-light m-1">
                                        Modifier</button></a>
                            </td>

                        </tr>
                        {% endfor %}

                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
    <a style="margin-right: 900px" href="{{ path('absence_chart') }}" class="btn btn-sm btn-primary btn-create"> voire les statistiques </a>
    {% endif %}
{% endblock %}

src/AbsenceBundle/Resources/views/Default/stat.html.twig
{% extends "::back/common/layout.html.twig" %}

{% block body %}
    {% if app.user.hasRole('ROLE_SUPER_ADMIN') %}
    <div class="gap gap"></div>

    <div class="container" style="margin-top: 150px">
        <div class="row">

            <p style="color: black"> Nombre de sceance par jour</p>
            <br>
            <br>



            <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
            <div class="col-md-9" class="chartjs-wrapper"><canvas id="chartjs-1" class="chartjs" width="undefined" height="undefined"></canvas>
                <script>
                    var dataSQL=[];
                    var dataNames=[];
                </script>
                {% for seance in seances %}


                        <script>
                            dataSQL.push({{ seance.num }});
                            dataNames.push("{{ seance.jour}}");
                     </script>

                {% endfor %}

                <div class="chartjs-wrapper"><canvas id="chartjs-1" class="chartjs" width="undefined" height="undefined"></canvas>
                    <script>new Chart(document.getElementById("chartjs-1"),{"type":"bar","data":{"labels":dataNames,"datasets":[{"label":"nombre seance","data":dataSQL,"fill":false,
                                    "backgroundColor":["rgba(87, 147, 250, 0.97)","rgba(87, 147, 250, 0.97)","rgba(255, 205, 86, 0.2)","rgba(75, 192, 192, 0.2)","rgba(54, 162, 235, 0.2)","rgba(153, 102, 255, 0.2)","rgba(201, 203, 207, 0.2)"],
                        "borderColor":["rgba(87, 147, 250, 0.97)","rgba(87, 147, 250, 0.97)","rgb(255, 205, 86)","rgb(75, 192, 192)","rgb(54, 162, 235)","rgb(153, 102, 255)","rgb(201, 203, 207)"],"borderWidth":1}]},
                        "options":{"scales":{"yAxes":[{"ticks":{"beginAtZero":true}}]}}});</script></div>



            </div>
        </div>

    </div>
   {% endif %}


{% endblock %}

src/AbsenceBundle/Resources/views/Default/updateabs.html.twig
{% extends "::front/common/layout.html.twig" %}
{% block body %}
    <div class="postbar postbarNone post-5426 page type-page status-publish hentry">
        {% block header %}
            <div class="page-header">
                <noscript>
                    <img alt="Events"
                         class="page-header-img"/>
                </noscript>
                <img alt="Events" class="page-header-img lazyloaded"
                     data-src="{{ asset('wp-content/uploads/2018/05/milan-2698731_1920-1500x750.jpg') }}"
                     src="{{ asset('wp-content/uploads/2018/05/milan-2698731_1920-1500x750.jpg') }}">
                <div class="container"><h1 class="give-form-title entry-title" itemprop="headline">Gestion Absence</h1>
                </div>
            </div>
        {% endblock %}
{% block content %}

<form method="POST">
    {#heure : <input type ="text"name="heure"value={{ sceance.heure|date }}>#}
    absence  : <input type ="text"name="absence"value={{ absence.absence}}>

    <input type ="submit" value="Enregistrer">
</form>
{% endblock %}
{% endblock %}